In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('/content/drive/MyDrive/슬기로운 건강생활/혈압·혈당 데이터.csv', encoding='cp949')
df

성별  연령  수축기혈압  이완기혈압  공복혈당  질병   BMI
0        1  27    146     50   168   3  20.8
1        1  19    138     50   109   4  22.6
2        1  27    130     50    71   2  16.6
3        1  27    129     50   115   1  20.3
4        1  25    127     50    97   4  24.1
...     ..  ..    ...    ...   ...  ..   ...
999995   2  11    150    120   108   2  30.8
999996   2  13    150    120   108   2  29.7
999997   2  24    150    120   125   4  26.8
999998   2   9    140    120    83   4  26.9
999999   2  22    140    120   125   2  23.3

[1000000 rows x 7 columns]

In [5]:
df.isnull().sum()

성별       0
연령       0
수축기혈압    0
이완기혈압    0
공복혈당     0
질병       0
BMI      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 7 columns):
 #   Column  Non-Null Count    Dtype  
---  ------  --------------    -----  
 0   성별      1000000 non-null  int64  
 1   연령      1000000 non-null  int64  
 2   수축기혈압   1000000 non-null  int64  
 3   이완기혈압   1000000 non-null  int64  
 4   공복혈당    1000000 non-null  int64  
 5   질병      1000000 non-null  int64  
 6   BMI     1000000 non-null  float64
dtypes: float64(1), int64(6)
memory usage: 53.4 MB


In [9]:
train=df

In [10]:
# feature와 target 분리
yt=np.array(train['질병'])
xt=train.drop(['질병'], axis=1)
xt=np.array(xt)

# 데이터 정규화
scaler=MinMaxScaler()
xt=scaler.fit_transform(xt)

# train test 데이터 split
xtrain,xtest,ytrain,ytest=train_test_split(xt, yt, test_size=0.2, random_state=42)

In [11]:
# 랜덤포레스트 without tuning
rf = RandomForestClassifier(random_state=17)
rf.fit(xtrain, ytrain)
forest_predictions = rf.predict(xtest)

accuracy_score(ytest, forest_predictions)
forest_predictions = rf.predict(xtest)

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [13]:
# 데이터 100만 개 사용

print(confusion_matrix(ytest, forest_predictions))

[[  3271   2793   1301   3471]
 [  1530  10915    506  19409]
 [  1743   1124   1758   3965]
 [  1382   9550   1285 135997]]


In [14]:
print(classification_report(ytest, forest_predictions))

              precision    recall  f1-score   support

           1       0.41      0.30      0.35     10836
           2       0.45      0.34      0.38     32360
           3       0.36      0.20      0.26      8590
           4       0.84      0.92      0.87    148214

    accuracy                           0.76    200000
   macro avg       0.51      0.44      0.47    200000
weighted avg       0.73      0.76      0.74    200000



In [16]:
print(classification_report(ytest, forest_predictions))
accuracy = accuracy_score(ytest, forest_predictions)
accuracy

              precision    recall  f1-score   support

           1       0.41      0.30      0.35     10836
           2       0.45      0.34      0.38     32360
           3       0.36      0.20      0.26      8590
           4       0.84      0.92      0.87    148214

    accuracy                           0.76    200000
   macro avg       0.51      0.44      0.47    200000
weighted avg       0.73      0.76      0.74    200000



0.759705